### ISSUE TITLE
Update README for Go modules

### ISSUE THREAD

**Issue by metalmatze** [google/go-jsonnet#273] opened 2019-05-03 17:13 UTC
It seems the project switched to using Go modules and I've tried to use it that way in my CI.

`go get github.com/google/go-jsonnet/cmd/jsonnet@v0.12.1`
My env vars are `GO111MODULE: 'on'` and I even enabled `GOPROXY: 'https://proxy.golang.org'` for faster CI builds. 

Sadly it fails to install with: 
```
[generate:22] go get github.com/google/go-jsonnet/cmd/jsonnet@v0.12.1: unknown revision cmd/jsonnet/v0.12.1
```

I'm not entirely sure how to `go get` this project right now...
Any ideas?

**Comment by michaeljs1990** [comment] 2019-05-05 20:09
If you are importing this into a go module you can't use a version with a sub path of a module. If you could do a specific version per path things would get messy very quickly although possibly a better error message should be output. Note the following works and will do what you want.

If you want to globally install the binary you must do it from master.

```
go get github.com/google/go-jsonnet@v0.12.1
```

**Comment by metalmatze** [comment] 2019-05-06 12:04
Good point on not being able to install sub paths. This was mostly about installing the binary globally from a specific version.
I guess I need to create a work around, like Prometheus uses, to be able to version the binary then: https://github.com/prometheus/prometheus/blob/375ad1185c128e947dbf75000024088c504a0b14/scripts/tools.go#L16

**Comment by michaeljs1990** [comment] 2019-05-06 14:46
Ah that is interesting. I have not seen that before. Are you set on using the `go` tooling for installing this or would a pre-built binary also solve your issues? I have been using nix-shell for situations like recently.

**Comment by metalmatze** [comment] 2019-05-07 16:14
A pre-built binary would resolve my problems too. Something in a container is actually easiest for me.

**Comment by michaeljs1990** [comment] 2019-05-07 21:12
@sbarzowski do you have any reservations about providing binaries from the release page on this repo?

I can add support for building the release binaries via BAZEL similar to what I did in [this repo](https://github.com/michaeljs1990/collins-go-cli). Gox is also common for this and people may be more familiar with that. The nice thing about bazel is you can build your production release without your test dependencies and files being globed in.

**Comment by sbarzowski** [comment] 2019-05-07 21:47
> do you have any reservations about providing binaries from the release page on this repo?
It would be very nice to have that IMO and people asked for it a few times already.

Do I understand correctly that the point of Bazel (instead of just go build) is cross compilation? I have never tried cross-compiling Go programs. Does it work better than setting $GOOS and $GOARCH envvars and using `go build`?

**Comment by michaeljs1990** [comment] 2019-05-08 04:33
The reasons for bazel in my opinion would be

1. Fine grain control over your build outputs. (i.e. You can normally trim a few MB of your binary by not including any of your testing dependencies).
2. You can make the build hermetic down to the version of go your are compiling your files with.
3. As long as you have bazel installed it's just one command to build everything and it should encompass all the dependencies needed for the build as well.

With bazel some of the setbacks will be that moving around source files will require changes to build files as well. It's also going to be a different build system than you use for normal development unless you really feel like going all in on bazel.

As you mentioned though GOOS / GOARCH and a makefile will get the job done as well. I'm not selling bazel very hard because for golang projects it really does come down to it being a system that you like using which is why I use it for my go projects.

**Comment by metalmatze** [comment] 2019-05-08 07:55
Yeah, I get the idea of basel, but think in this case a simple `go build` with GOOS and GOARCH is fine. If it's a shell script or a Makefile, I don't really care. It would be nice to have pre-build binaries for sure.

**Comment by sparkprime** [comment] 2019-05-08 09:21
I would avoid bazel unless it's your life, your world, your passion :)

**Comment by michaeljs1990** [comment] 2019-05-13 04:56
I was messing around with this for a little bit tonight and came up with the following Makefile that we could use for releases with `make release`.

```
BINS_DIR = bins
VERSION = $(shell git describe --tag --dirty)
SRC = $(shell find . -type f -name '*.go')

# Add GOOS_GOARCH here
PLATFORMS = \
        linux_amd64

BINS_OUT = $(patsubst %, $(BINS_DIR)/$(VERSION)/jsonnet-%, $(PLATFORMS))

$(BINS_DIR)/$(VERSION):
        mkdir -p $(BINS_DIR)/$(VERSION)

$(BINS_OUT): $(BINS_DIR)/$(VERSION) $(SRC)
        $(eval BINARY = $(notdir $@))
        $(eval PARTS = $(word 2, $(subst -, ,$(BINARY))))
        $(eval BUILD = $(subst _, ,$(PARTS)))
        CGO_ENABLED=0 GOOS=$(word 1, $(BUILD)) GOARCH=$(word 2, $(BUILD)) go build -o $@ ./cmd/jsonnet

.PHONY: release
release: $(BINS_OUT)

.PHONY: clean
clean:
        rm -rf $(BINS_DIR)
```

I'm looking at the best way to setup travis CI to push back to the repo. They use an encrypted string for the API key but i'm trying to find if a better way is available to give travis the ability to publish releases.

**Comment by sbarzowski** [comment] 2020-02-02 16:34
We have a section in the README on installing with Go modules and I created a separate issue for tracking binary releases. I'm going to close this now, but feel free to reopen if the issue is still relevant.

**Closed by sbarzowski** 2020-02-02 16:34 UTC
