### ISSUE TITLE
Help finding missing comma

### ISSUE THREAD

**Issue by ghostsquad** [google/go-jsonnet#406] opened 2020-05-04 17:23 UTC
Sometimes I'll see an error for `Expected a comma before next field`. The trace is at the _bottom_ of my file, and it's incredibly hard to find where I'm missing the comma. Any hints or tips on how to solve this problem?

Additionally, is there anything on the roadmap to potentially make this easier to deal with?

**Comment by sbarzowski** [comment] 2020-05-04 18:03
That doesn't sound right. In the toy example I have just tried it worked as expected (i.e the location of the missing comma error was the first token after the missing comma). Could you provide an example where the problem appears?

Does the same problem appear in C++ implementation? (You can check that by copy-pasting the contents into an interactive example on jsonnet.org if you don't have it installed).

**Comment by ghostsquad** [comment] 2020-05-04 18:07
I found the problem (ish), but not the solution:

I have a big nested if/else/else if and I think I'm doing it wrong

```
if std.isArray(stages)
then (
  if $.isArrayOfType(stages, "string")
  then stages
  else
    std.map(
      function(stage) (
        stage.refId
      ),
      stages
    )
)
else if std.isString(stages)
then
  [ stages ]
else if std.isObject(stages)
then
  [ stages.refId ]
else
  error ("expected array, string or object, got: %s" % [ std.type(stages) ])
```

**Comment by ghostsquad** [comment] 2020-05-04 18:20
I've confirmed that this is happening in the C++ version (brew install | /usr/local/bin/jsonnet) as well as Go version 

```
pipeline.libsonnet:471:1: expected a comma before next field.
```

My file is exactly 471 lines long

so.. it wasn't the if statement. I had something like this:

```
{
  foo: {
    bar: "blah

  baz: {

  }
}
```

notice the missing closing bracket for `foo`. There might not be anything that can be done in this case

**Comment by sbarzowski** [comment] 2020-05-04 18:26
Is the missing `"` intentional as well? I guess not.

**Comment by sbarzowski** [comment] 2020-05-04 18:46
I'm getting a reasonable error location after adding just the missing `"`.

This one is problematic, though:
```
{
  foo: {
    bar: "blah",

  baz: {

  }
}
```
It actually shows the end of the file as the location of the problem.  Note that there actually is a comma after `bar` definition. The bracket is missing, so it thinks that we are still inside the definition of `foo`. Everything is valid Jsonnet until we reach the final bracket (at this point Jsonnet "thinks" we are still inside the top-level object and complains). I don't think we could fix that one easily, because if you added a closing bracket at the end, the program would actually be valid. There is one way we can notice the problem - it is actually misindented now. The problem is that `jsonnetfmt` won't help you with programs which are not syntactically valid.

I'm afraid almost all programming languages implementations will show misleading error location in some cases - it's not always possible to guess the intention behind the malformed program. You could reduce the chance of encountering such problems by avoiding deep nesting in favor of functions, locals, imports etc.

In particular big nested if-then-else is probably not the most convenient way to structure your programs. You may consider naming some of the subexpressions. In Jsonnet `local x = <expr>, y = <expr2>; if <cond> then x else y` is precisely equivalent to `if <cond> then <expr1> else <expr2>`.

**Comment by ghostsquad** [comment] 2020-05-04 21:57
ya, sorry for the false alarm here..

I'm finding that the best way to debug some of this stuff is to just comment out a bunch stuff, and slowly uncomment it out until you find it.

Many of the folks I work with don't like jsonnet because it can be very hard to debug sometimes.

> You could reduce the chance of encountering such problems by avoiding deep nesting in favor of functions, locals, imports etc.

Indeed, that's something that I like to do, but it's not always possible to keep it shallow, since the data structure is entirely dependent on the tool/system you are working in (like Kubernetes manifests).

I think a series of best practices for styling would go a _long_ way to help find these kinds of things.

One thing to note also, that even being shallow, there's also the problem of having "long" objects, and also styling when you are calling functions within functions. Example:

```jsonnet
{
   foo(thing): {
	  # 100 more lines

	  WithWhatever():: self + {
        # stuff
      }
   },
   
   aReallyLongKeyHereMakesMeWantToStartANewLine:
     foo(newThing()
          .WithWhatever()
     )
}
```

The second part of this can make it hard to realize where you are at. I'm not even sure what style really should be in this case...

**Comment by sbarzowski** [comment] 2020-05-22 10:51
I don't see anything actionable for us here (other than having an official style guide, which is tracked separately), so I'm going to close this issue.

**Closed by sbarzowski** 2020-05-22 10:51 UTC
