### ISSUE TITLE
manifest as single-line json?

### ISSUE THREAD

**Issue by ghostsquad** [google/go-jsonnet#400] opened 2020-04-13 23:44 UTC
Is there a function like `manifestJsonEx` but which returns a value that that is a single line? (does not have `\n` in it that are part of the json structure itself)

**Comment by sbarzowski** [comment] 2020-04-14 08:35
Closing as duplicate of https://github.com/google/jsonnet/issues/796. 

For general language questions and feature requests it's enough to open the issue in one of the repos.

**Closed by sbarzowski** 2020-04-14 08:35 UTC
