### ISSUE TITLE
using importstr to read normal text files as templates

### ISSUE THREAD

**Issue by ymolists** [google/go-jsonnet#249] opened 2018-11-03 23:07 UTC
go version go1.11 linux/amd64

cat test.ts:
replicas: %(replicas),

cat foo.jsonnet:
{
  'foo.ts': (importstr "test.ts") % { replicas: "2" } ,
}

jsonnet -S -m . foo.jsonnet

RUNTIME ERROR: Unrecognised conversion type: ,
        <std>:417:11-53 function <parse_conv_type>
        <std>:430:23-52 thunk <ctype> from <function <parse_code>>
        <std>:432:14-19 object <anonymous>
        <std>:451:28-31 thunk from <function <parse_codes>>
        <std>:451:11-57 function <parse_codes>
        <std>:455:19-46 thunk <codes> from <function <anonymous>>
        <std>:745:24-29 thunk from <function <anonymous>>
        <std>:703:26-31 thunk from <function <format_codes_obj>>
        <std>:703:15-32 function <format_codes_obj>
        <std>:745:7-43  function <anonymous>
        <std>:225:7-23  function <anonymous>

        During manifestation

**Comment by seh** [comment] 2018-11-04 00:07
You're missing [a conversion type specifier](https://docs.python.org/2/library/stdtypes.html#string-formatting-operations) after "%(replicas)" in your _test.ts_ file. Add an 's' character after the closing parenthesis and it works as expected, though I'm not sure if that trailing comma after the closing parenthesis was intended.

**Closed** 2018-11-05 11:34 UTC
