### ISSUE TITLE
Failure to render kube-prometheus jsonnet on CircleCI

### ISSUE THREAD

**Issue by thejosephstevens** [google/go-jsonnet#299] opened 2019-07-23 23:17 UTC
Running jsonnet 0.13.0

After running this on CircleCI
```
FATAL: Command 'jsonnet -J monitoring/kube-prometheus/vendor -m monitoring/kube-prometheus/manifests-generated/json --tla-str 'Host=myHostName' --tla-str 'environment=gcp' monitoring/kube-prometheus/compute.jsonnet' returned non-zero exit status 1.
```

This error was output. I'm unable to reproduce the issue locally and I have not been able to identify a version I can switch that will fix it (have played with kube-prometheus version, have tried jsonnet 0.12.1, have tried bumping etcd-mixin to master)
```
INTERNAL ERROR: (CRASH) runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc008d185d8, 0x5609c0, 0x6e3c00)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc008d21d00)
	/go/src/github.com/google/go-jsonnet/vm.go:129 +0x60
panic(0x5609c0, 0x6e3c00)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/google/go-jsonnet.makeValueExtendedObject(0xc008770090, 0xc008755920, 0x1)
	/go/src/github.com/google/go-jsonnet/value.go:585 +0x5d
github.com/google/go-jsonnet.builtinPlus(0xc0000cc140, 0xc0001fdf00, 0xc0001690c0, 0x5dcde0, 0xc008770090, 0x5dcde0, 0xc008755920, 0x5dcde0, 0xc008770090, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/builtins.go:61 +0x174
github.com/google/go-jsonnet.(*PlusSuperUnboundField).evaluate(0xc0005b8780, 0xc0000cc140, 0xc0001fdf00, 0xc0001690c0, 0xc0007053e0, 0x0, 0xc0087555f0, 0xc0045083a0, 0x11, 0xc0007052f0, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:139 +0x216
github.com/google/go-jsonnet.objectIndex(0xc0000cc140, 0xc0001fdf00, 0xc0001690c0, 0xc0007053e0, 0x0, 0xc0045083a0, 0x11, 0x0, 0x4f001e3e26786b0b, 0x8, ...)
	/go/src/github.com/google/go-jsonnet/value.go:659 +0x2a2
github.com/google/go-jsonnet.(*valueObject).index(...)
	/go/src/github.com/google/go-jsonnet/value.go:432
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de2e0, 0xc0001fdf00, 0x1, 0x1, 0xc0087555c0, 0x408300, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:443 +0xc8b
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc00024e280, 0xc000253240, 0xc008d19088, 0x5de2e0, 0xc0001fdf00, 0xc0007a7500, 0xc0007a75f0, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*codeUnboundField).evaluate(0xc00078c8a0, 0xc0000cc140, 0xc00024e280, 0xc000253240, 0xc00039b9e0, 0x1, 0xc0087555c0, 0xc003e8a140, 0xa, 0xc00039b770, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:100 +0x9c
github.com/google/go-jsonnet.objectIndex(0xc0000cc140, 0xc00024e280, 0xc000253240, 0xc00039b9e0, 0x0, 0xc003e8a140, 0xa, 0x0, 0x7d8c00, 0x6d4570, ...)
	/go/src/github.com/google/go-jsonnet/value.go:659 +0x2a2
github.com/google/go-jsonnet.(*valueObject).index(...)
	/go/src/github.com/google/go-jsonnet/value.go:432
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de2e0, 0xc00024e280, 0x1, 0x1, 0xc008755440, 0xc008755500, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:443 +0xc8b
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0x7136e0, 0x6d1d90, 0xc0074de2c0, 0x5de2e0, 0xc00024e280, 0xc0000c1100, 0xc004508200, 0xe, 0xc00011b0a8, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc003e8c240, 0xc0000cc140, 0x7136e0, 0x6d1d90, 0x7b08e0, 0xc008d199a8, 0x443ce3, 0x7bf160)
	/go/src/github.com/google/go-jsonnet/thunks.go:76 +0x8c
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de620, 0x7136e0, 0x1, 0x1, 0xc008755500, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:508 +0x113a
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0x7c6000, 0x6d1d80, 0xc0074de340, 0x5de620, 0x7136e0, 0xc008d1a000, 0x3, 0x3, 0xc0043694d0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc003e8c2c0, 0xc0000cc140, 0x7c6000, 0x6d1d80, 0xe, 0x58d11d, 0x1, 0xc0043694d0)
	/go/src/github.com/google/go-jsonnet/thunks.go:76 +0x8c
github.com/google/go-jsonnet.(*binaryBuiltin).EvalCall(0xc0000c0480, 0xc0049d0890, 0x2, 0x2, 0x80a100, 0x0, 0x0, 0x0, 0xc0000cc140, 0x7c6000, ...)
	/go/src/github.com/google/go-jsonnet/builtins.go:982 +0x208
github.com/google/go-jsonnet.(*valueFunction).call(0xc0000930a0, 0xc0000cc140, 0x7c6000, 0x6d1d80, 0xc0049d0890, 0x2, 0x2, 0x80a100, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000cc140, 0xc0000930a0, 0xc0049d0890, 0x2, 0x2, 0x80a100, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5ddf60, 0x7c6000, 0x1, 0x1, 0xc0087554a0, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:563 +0x3165
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc000202b40, 0xc000252f20, 0xc0074de300, 0x5ddf60, 0x7c6000, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*closure).EvalCall(0xc008780b40, 0xc001141308, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0xc0000cc140, 0xc000202b40, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:204 +0x4ba
github.com/google/go-jsonnet.(*valueFunction).call(0xc004cdec90, 0xc0000cc140, 0xc000202b40, 0xc000252f20, 0xc001141308, 0x1, 0x1, 0x80a100, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000cc140, 0xc004cdec90, 0xc001141308, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5ddf60, 0xc000202b40, 0x1, 0x1, 0xc008755380, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:563 +0x3165
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc00025b7c0, 0x0, 0xc0074de280, 0x5ddf60, 0xc000202b40, 0xc008d1b200, 0x5dcd20, 0xc0049d0880, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc003e8c180, 0xc0000cc140, 0xc00025b7c0, 0x0, 0x5dcd20, 0xc0049d0880, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/thunks.go:76 +0x8c
github.com/google/go-jsonnet.(*binaryBuiltin).EvalCall(0xc0000c0360, 0xc0049d0860, 0x2, 0x2, 0x80a100, 0x0, 0x0, 0x0, 0xc0000cc140, 0xc00025b7c0, ...)
	/go/src/github.com/google/go-jsonnet/builtins.go:986 +0x283
github.com/google/go-jsonnet.(*valueFunction).call(0xc000092cc0, 0xc0000cc140, 0xc00025b7c0, 0x0, 0xc0049d0860, 0x2, 0x2, 0x80a100, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000cc140, 0xc000092cc0, 0xc0049d0860, 0x2, 0x2, 0x80a100, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5ddf60, 0xc00025b7c0, 0x1, 0xc003e2f9d0, 0xc008755350, 0xc008d1bb98, 0x443ce3)
	/go/src/github.com/google/go-jsonnet/interpreter.go:563 +0x3165
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de420, 0xc00024e300, 0x1, 0x1, 0xc0087552f0, 0x408300, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:497 +0x41b
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc00014ca80, 0xc000168b80, 0xc008d1c210, 0x5de420, 0xc00024e300, 0xc0007a7c00, 0xc0007a7c70, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*codeUnboundField).evaluate(0xc00078c9b0, 0xc0000cc140, 0xc00014ca80, 0xc000168b80, 0xc00039be00, 0x1, 0xc0087552f0, 0xc004508080, 0x14, 0xc00039bd10, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:100 +0x9c
github.com/google/go-jsonnet.objectIndex(0xc0000cc140, 0xc00014ca80, 0xc000168b80, 0xc00039be00, 0x1, 0xc004508080, 0x14, 0x0, 0x203000, 0x576320, ...)
	/go/src/github.com/google/go-jsonnet/value.go:659 +0x2a2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de5a0, 0xc00014ca80, 0x1, 0x0, 0xc008754e10, 0xc008755200, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:519 +0x13f9
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc00171ae70, 0xc0044894a0, 0xc0074de0a0, 0x5de5a0, 0xc00014ca80, 0x7e2900, 0x7b1560, 0x7e42f0, 0xc0019ef860, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc003e03d00, 0xc0000cc140, 0xc00171ae70, 0xc0044894a0, 0xc0016653c0, 0xc004a54860, 0x516595, 0x576320)
	/go/src/github.com/google/go-jsonnet/thunks.go:76 +0x8c
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de620, 0xc00171ae70, 0x1, 0x0, 0xc008755230, 0xc008755200, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:508 +0x113a
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc00171afc0, 0xc004489520, 0xc0074de160, 0x5de620, 0xc00171ae70, 0x0, 0xc000112778, 0x1, 0xc0045f7280, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc003e03f00, 0xc0000cc140, 0xc00171afc0, 0xc004489520, 0xc001665480, 0x40bc18, 0x8, 0xc007415600)
	/go/src/github.com/google/go-jsonnet/thunks.go:76 +0x8c
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de620, 0xc00171afc0, 0x1, 0x0, 0xc0087552c0, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:508 +0x113a
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc00171c1e0, 0xc0044894e0, 0xc0074de1e0, 0x5de620, 0xc00171afc0, 0xc008d1d800, 0x3, 0x3, 0xc004508020, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc003e03f80, 0xc0000cc140, 0xc00171c1e0, 0xc0044894e0, 0x4, 0x58d11d, 0x1, 0xc004508020)
	/go/src/github.com/google/go-jsonnet/thunks.go:76 +0x8c
github.com/google/go-jsonnet.(*unaryBuiltin).EvalCall(0xc0000c0510, 0xc001141300, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0xc0000cc140, 0xc00171c1e0, ...)
	/go/src/github.com/google/go-jsonnet/builtins.go:933 +0x20d
github.com/google/go-jsonnet.(*valueFunction).call(0xc000092c40, 0xc0000cc140, 0xc00171c1e0, 0xc0044894e0, 0xc001141300, 0x1, 0x1, 0x80a100, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000cc140, 0xc000092c40, 0xc001141300, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5ddf60, 0xc00171c1e0, 0x0, 0x4, 0x7bf160, 0x1, 0x5dce20)
	/go/src/github.com/google/go-jsonnet/interpreter.go:563 +0x3165
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de0a0, 0xc001719480, 0x0, 0xc008d1e7d0, 0x516207, 0xc008d1e7d0, 0x40bc18)
	/go/src/github.com/google/go-jsonnet/interpreter.go:330 +0x28cd
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de0e0, 0xc00170a3f0, 0x1, 0x5dcde0, 0xc008754d80, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:358 +0x3923
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de0a0, 0xc001719680, 0x1, 0x0, 0xc008755290, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:334 +0x2932
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc00171c0a0, 0xc004489440, 0xc0074de1a0, 0x5de0a0, 0xc001719680, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*closure).EvalCall(0xc0050e94f0, 0xc0011412f8, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0xc0000cc140, 0xc00171c0a0, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:204 +0x4ba
github.com/google/go-jsonnet.(*valueFunction).call(0xc0049d0840, 0xc0000cc140, 0xc00171c0a0, 0xc004489440, 0xc0011412f8, 0x1, 0x1, 0x80a100, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000cc140, 0xc0049d0840, 0xc0011412f8, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5ddf60, 0xc00171c0a0, 0x1, 0x5dcde0, 0xc008755170, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:563 +0x3165
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de0a0, 0xc001719300, 0x1, 0x0, 0xc008754e70, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:334 +0x2932
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc000149ae0, 0xc000168b40, 0xc0074de0c0, 0x5de0a0, 0xc001719300, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*closure).EvalCall(0xc0050e94a0, 0xc0011412e8, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0xc0000cc140, 0xc000149ae0, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:204 +0x4ba
github.com/google/go-jsonnet.(*valueFunction).call(0xc0049d0800, 0xc0000cc140, 0xc000149ae0, 0xc000168b40, 0xc0011412e8, 0x1, 0x1, 0x80a100, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000cc140, 0xc0049d0800, 0xc0011412e8, 0x1, 0x1, 0x80a100, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5ddf60, 0xc000149ae0, 0x1, 0x0, 0xc008754c60, 0x408300, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:563 +0x3165
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc000141680, 0xc000142c70, 0xc008d20cf0, 0x5ddf60, 0xc000149ae0, 0xc0007a7000, 0xc0007a7040, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*codeUnboundField).evaluate(0xc00078c810, 0xc0000cc140, 0xc000141680, 0xc000142c70, 0xc00039be00, 0x0, 0xc008754c60, 0xc004515f00, 0x14, 0xc00039b4a0, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:100 +0x9c
github.com/google/go-jsonnet.objectIndex(0xc0000cc140, 0xc000141680, 0xc000142c70, 0xc00039be00, 0x0, 0xc004515f00, 0x14, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:659 +0x2a2
github.com/google/go-jsonnet.(*valueObject).index(...)
	/go/src/github.com/google/go-jsonnet/value.go:432
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000cc140, 0x5de2e0, 0xc000141680, 0x1, 0x0, 0xc008754c30, 0xc000798e00, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:443 +0xc8b
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000cc140, 0xc0007ae180, 0x0, 0xc008d21590, 0x5de2e0, 0xc000141680, 0x0, 0x90000c0007aa540, 0xc0007a94d8, 0x560660, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:916 +0xbb
github.com/google/go-jsonnet.(*codeUnboundField).evaluate(0xc00078cab0, 0xc0000cc140, 0xc0007ae180, 0x0, 0xc0007aaa50, 0x0, 0xc008754c30, 0xc000521520, 0x1c, 0xc0007a58c0, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:100 +0x9c
github.com/google/go-jsonnet.(*bindingsUnboundField).evaluate(0xc000886980, 0xc0000cc140, 0xc0007ae180, 0x0, 0xc0007aaa50, 0x0, 0xc008754bd0, 0xc000521520, 0x1c, 0xc0007aa900, ...)
	/go/src/github.com/google/go-jsonnet/thunks.go:119 +0x259
github.com/google/go-jsonnet.objectIndex(0xc0000cc140, 0xc0007ae180, 0x0, 0xc0007aaa50, 0x0, 0xc000521520, 0x1c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/google/go-jsonnet/value.go:659 +0x2a2
github.com/google/go-jsonnet.(*valueObject).index(...)
	/go/src/github.com/google/go-jsonnet/value.go:432
github.com/google/go-jsonnet.(*interpreter).manifestJSON(0xc0000cc140, 0xc0007ae180, 0x0, 0x5dcde0, 0xc0007aaa50, 0x0, 0x0, 0x0, 0xc000ac1a40)
	/go/src/github.com/google/go-jsonnet/interpreter.go:671 +0x50a
github.com/google/go-jsonnet.(*interpreter).manifestAndSerializeMulti(0xc0000cc140, 0xc0007ae180, 0x0, 0x5dcde0, 0xc0007aaa50, 0xc0007aaa00, 0xc0007ae180, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/interpreter.go:814 +0x88
github.com/google/go-jsonnet.evaluateMulti(0x5de420, 0xc0000f8280, 0xc0000c0a80, 0xc0000c0ab0, 0xc0000c0ae0, 0x1f4, 0x5dbe80, 0xc00000c280, 0x0, 0xc00008dcb0, ...)
	/go/src/github.com/google/go-jsonnet/interpreter.go:1251 +0x121
github.com/google/go-jsonnet.(*VM).evaluateSnippet(0xc0000cc050, 0x7ffc966ef415, 0x2a, 0xc0000200b0, 0xa1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/google/go-jsonnet/vm.go:140 +0x253
github.com/google/go-jsonnet.(*VM).EvaluateSnippetMulti(0xc0000cc050, 0x7ffc966ef415, 0x2a, 0xc0000200b0, 0xa1, 0x100, 0xc000014340, 0x34)
	/go/src/github.com/google/go-jsonnet/vm.go:186 +0x69
main.main()
	/go/src/github.com/google/go-jsonnet/cmd/jsonnet/cmd.go:549 +0xd84

Please report a bug here: https://github.com/google/go-jsonnet/issues
```

I'm going to keep debugging, please let me know if there's anything else it would be useful for me to provide.

**Comment by sbarzowski** [comment] 2019-07-23 23:31
@thejosephstevens Thanks a lot for reporting. This is a big deal and I'll try to fix it ASAP. 

Do I understand correctly that the same error occurs on both 0.13.0 and 0.12.1? Could you also check what happens on master? The stack trace you pasted - is it from 0.13.0?

If the files that it crashes on are not confidential could you please share them? (If you prefer sharing it privately, you can reach me on kubernetes.slack.com or you can send me an email).

Of course a minimal example which allows reproducing the problem would be even better (that's what I would probably need to start with anyway).

**Comment by thejosephstevens** [comment] 2019-07-24 02:45
Just for context, I've narrowed down the issue on my end and sent the offending files to @sbarzowski . It looks like a bad array dereference, but it's still not clear why it's behaving differently on our laptops vs on CircleCI.

**Comment by sbarzowski** [comment] 2019-07-24 06:47
Ok, I was able to reproduce.

Apparently your CI runs on master version of Jsonnet. A big change has just been merged (not a part of any release yet) and you caught a problem with it (which our tests missed :-/). It's somewhat unfortunate that the reported version of current master is just the last release (we really should report v0.13.0 only for the specific 0.13.0 commit).

> why it's behaving differently on our laptops vs on CircleCI.

Jsonnet tries really hard to be independent of the environment, so I suspected that it will boil down to a different version and it's the first thing I tested.

I'll be working on a fix. You shouldn't need to change anything on your end.

**Comment by sbarzowski** [comment] 2019-07-24 07:51
Ok, I think I found the root cause. There is a boundary case when an empty object comprehension is added to something.
```
./jsonnet -e '{} + { [x]: 42 for x in [] }'
```

I'll push a fix soon

**Comment by thejosephstevens** [comment] 2019-07-24 17:04
Ah, yeah, a granular version number or reporting an annotation by git sha might've made it easier to tell what was going on. Awesome work though, thanks for getting this fixed so quickly!

**Comment by ghostsquad** [comment] 2019-12-14 04:09
Should this issue be closed now that the problem is fixed?

**Comment by sbarzowski** [comment] 2019-12-14 07:35
Right, thanks

**Closed by sbarzowski** 2019-12-14 07:35 UTC
